// <auto-generated />
using System;
using Mercadados_API.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mercadados_API.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20251007132044_MercaDados")]
    partial class MercaDados
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mercadados_API.Domains.Estoque", b =>
                {
                    b.Property<Guid>("EstoqueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EstoqueProdutosID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProdutosID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INT");

                    b.Property<string>("Setor")
                        .IsRequired()
                        .HasColumnType("Varchar(200)");

                    b.HasKey("EstoqueID");

                    b.HasIndex("EstoqueProdutosID")
                        .IsUnique()
                        .HasFilter("[EstoqueProdutosID] IS NOT NULL");

                    b.ToTable("Estoque");
                });

            modelBuilder.Entity("Mercadados_API.Domains.EstoqueProdutos", b =>
                {
                    b.Property<Guid>("EstoqueProdutosID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EstoqueID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProdutosID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuantidadeEstoque")
                        .HasColumnType("Int");

                    b.HasKey("EstoqueProdutosID");

                    b.ToTable("EstoqueProdutos");
                });

            modelBuilder.Entity("Mercadados_API.Domains.Feedback", b =>
                {
                    b.Property<Guid>("FeedbackID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataFeedback")
                        .HasColumnType("DATETIME");

                    b.Property<string>("Nota")
                        .IsRequired()
                        .HasColumnType("Varchar(200)");

                    b.Property<Guid>("UsuarioID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FeedbackID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("Mercadados_API.Domains.ItemVenda", b =>
                {
                    b.Property<Guid>("ItemVendaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Data")
                        .HasColumnType("DATE");

                    b.Property<double>("Preco")
                        .HasColumnType("FLOAT");

                    b.Property<Guid>("ProdutosID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VendaID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ItemVendaID");

                    b.HasIndex("ProdutosID");

                    b.HasIndex("VendaID");

                    b.ToTable("ItemVenda");
                });

            modelBuilder.Entity("Mercadados_API.Domains.Produtos", b =>
                {
                    b.Property<Guid>("ProdutoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EstoqueProdutosID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("Varchar(200)");

                    b.Property<double>("Preco")
                        .HasColumnType("FLoat");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INT");

                    b.HasKey("ProdutoID");

                    b.HasIndex("EstoqueProdutosID")
                        .IsUnique();

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("Mercadados_API.Domains.TipoUsuario", b =>
                {
                    b.Property<Guid>("TipoUsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TituloTipoUsuario")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("TipoUsuarioID");

                    b.ToTable("TipoUsuario");
                });

            modelBuilder.Entity("Mercadados_API.Domains.Usuario", b =>
                {
                    b.Property<Guid>("UsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("VARCHAR(14)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("VARCHAR(13)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<Guid>("TipoUsuarioID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UsuarioID");

                    b.HasIndex("TipoUsuarioID");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Mercadados_API.Domains.Venda", b =>
                {
                    b.Property<Guid>("VendaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FeedbackID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ItemVendaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INT");

                    b.Property<double>("Valor")
                        .HasColumnType("FLOAT");

                    b.HasKey("VendaID");

                    b.HasIndex("FeedbackID");

                    b.HasIndex("ItemVendaID")
                        .IsUnique()
                        .HasFilter("[ItemVendaID] IS NOT NULL");

                    b.ToTable("Venda");
                });

            modelBuilder.Entity("Mercadados_API.Models.Imagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Caminho")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Imagens");
                });

            modelBuilder.Entity("Mercadados_API.Domains.Estoque", b =>
                {
                    b.HasOne("Mercadados_API.Domains.EstoqueProdutos", "EstoqueProdutos")
                        .WithOne("Estoque")
                        .HasForeignKey("Mercadados_API.Domains.Estoque", "EstoqueProdutosID");

                    b.Navigation("EstoqueProdutos");
                });

            modelBuilder.Entity("Mercadados_API.Domains.Feedback", b =>
                {
                    b.HasOne("Mercadados_API.Domains.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Mercadados_API.Domains.ItemVenda", b =>
                {
                    b.HasOne("Mercadados_API.Domains.Produtos", "Produtos")
                        .WithMany()
                        .HasForeignKey("ProdutosID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mercadados_API.Domains.Venda", "Venda")
                        .WithMany()
                        .HasForeignKey("VendaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produtos");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("Mercadados_API.Domains.Produtos", b =>
                {
                    b.HasOne("Mercadados_API.Domains.EstoqueProdutos", "EstoqueProdutos")
                        .WithOne("Produtos")
                        .HasForeignKey("Mercadados_API.Domains.Produtos", "EstoqueProdutosID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstoqueProdutos");
                });

            modelBuilder.Entity("Mercadados_API.Domains.Usuario", b =>
                {
                    b.HasOne("Mercadados_API.Domains.TipoUsuario", "TipoUsuario")
                        .WithMany()
                        .HasForeignKey("TipoUsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoUsuario");
                });

            modelBuilder.Entity("Mercadados_API.Domains.Venda", b =>
                {
                    b.HasOne("Mercadados_API.Domains.Feedback", "Feedback")
                        .WithMany()
                        .HasForeignKey("FeedbackID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mercadados_API.Domains.ItemVenda", "ItemVenda")
                        .WithOne()
                        .HasForeignKey("Mercadados_API.Domains.Venda", "ItemVendaID");

                    b.Navigation("Feedback");

                    b.Navigation("ItemVenda");
                });

            modelBuilder.Entity("Mercadados_API.Domains.EstoqueProdutos", b =>
                {
                    b.Navigation("Estoque");

                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
